version: "3.7"
services:
  database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=car_post_storage"
    ports:
      - 5442:5432
    volumes:
      - pg-data:/data/postgres2
volumes:
  pg-data:
    driver: local